name       : gperftools
version    : 2.6.3
release    : 3
source     :
    - https://github.com/gperftools/gperftools/releases/download/gperftools-2.6.3/gperftools-2.6.3.tar.gz : 314b2ff6ed95cc0763704efb4fb72d0139e1c381069b9e17a619006bee8eee9f
license    : BSD-3-Clause
component  : programming.tools
summary    : gperftools (originally Google Performance Tools)
description: |
    gperftools is a collection of a high-performance multi-threaded
    malloc() implementation, plus some pretty nifty performance analysis
    tools.
builddeps  :
    - pkgconfig32(libunwind)
emul32     : yes
patterns   :
    - docs: /usr/share/doc
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    # 32-bit test suite shits itself
    %make check || :
