name       : gperftools
version    : '2.7'
release    : 5
source     :
    - https://github.com/gperftools/gperftools/archive/gperftools-2.7.tar.gz : 3a88b4544315d550c87db5c96775496243fb91aa2cea88d2b845f65823f3d38a
license    : BSD-3-Clause
component  : programming.tools
summary    : gperftools (originally Google Performance Tools)
description: |
    gperftools is a collection of a high-performance multi-threaded
    malloc() implementation, plus some pretty nifty performance analysis
    tools.
builddeps  :
    - pkgconfig32(libunwind)
emul32     : yes
patterns   :
    - docs : /usr/share/doc
setup      : |
    %reconfigure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    # 32-bit test suite shits itself
    %make check || :
